[[constraint]]
  name = "gopkg.in/src-d/go-mysql-server.v0"
  revision = "57fdfc0c19084e136736ec4cd804065e1b91bde2"

[[override]]
  name = "github.com/satori/go.uuid"
  revision = "36e9d2ebbde5e3f13ab2e25625fd453271d6522e"

[prune]
  non-go = true
  go-tests = true
  unused-packages = true
